### PR TITLE
Update hooks example to handle redirection

### PR DESCRIPTION
**Pull request by caseploeg**
Previously redirection information was lost by the postparsing hooks add_whitespace_hook() and downcase_hook(). This was fine for this simple shell, but sets a bad example for more complicated use cases. I made this mistake in my own application where I set up a hook to augment a Statement's arguments, but lost redirection information by accident. A *very* sticky bug to try and figure out why piping suddenly no longer works.

To fix this, when parsing the new Statement object, include the `post_command` attribute from the original Statement. I also made some slight organizational changes that should make it more obvious what's happening in the example.

I also add a postcommand hook that hopefully provides some more intuition on the hook lifecycle by updating the prompt with the raw contents of the command last entered. I have this feature locked behind the debug option. I imagine this could help someone figure out the consequences of registering new hooks.

related to #1000

### CODE REVIEW

**Review by anselor — APPROVED** [review]
Breaking things down in the example to improve clarity looks good.

**Comment by anselor** [comment]
@tleonhardt The lint check is failing on unrelated files. I think something in `black` must have changed on us?

**Comment by tleonhardt** [comment]
@anselor I merged in a fix for the `black` issues in unrelated files

**Comment by tleonhardt** [comment]
@casePloeg Thank you for the PR!  Please run `flake8` to fix linting issues and `black` to fix formatting ones and update the PR.

**Pull request merged**
