### PR TITLE
[Add] exit_with_error_code attribute

### PR DESCRIPTION
**Pull request by albertored**
**UNDER DEPLOYMENT - DO NOT MERGE**

I added an exception containing an exit code, that is used in `_cmdloop` for exiting the CLI with that exit code. The exception can be raised by users in custom commands or automatically for every command. This last feature can be activated by setting the class attribute `exit_with_error_code` to `True`.

I know it is on the wrong branch, if you think it's worth merging I will fix tests, and move to the right place.

See #358

### CODE REVIEW

**Comment by tleonhardt** [comment]
@albertored I'm not sure that I see this as been generally applicable to all situations.  When we can, we try to steer clear of design/implementation decisions which would in any way impact overall application architecture because we want developers to choose what makes sense for themselves.

If you want to take the time to clean it up, base it off of the correct branch, and get all of the tests to pass and add an example then I would be happy to take a look at it and maybe we can find a way to incorporate it that would make sense.  But I don't want you to waste your time.  My tentative thought is that perhaps this is left out of ``cmd2`` and up to the end user.

@kmvanbrunt or @kotfu do you have any thoughts on this?

**Comment by kmvanbrunt** [comment]
@albertored 
While this may a good feature for your application, it doesn't seem generic enough to be included in the cmd2 code. I have the same thing in my own cmd2-based applications. Many of the features I implement are nice for a particular program, but don't have the broader appeal needed for addition to cmd2.

**Comment by albertored** [comment]
I completely agree with you when you say that we should include in a library only features that can have a broad appeal for the users. If you think this is not a feature that can have this appeal I respect your choice but personally I disagree.
I disagree on the usefulness of the feature, this particular implementation can be totally ugly or wrong but I think having a way to detect when some command fails (not only seeing an error message) is useful.

I still don't see a way of implementing this in my own cmd2-based application only by overriding cmd2 methods... @kmvanbrunt if I understand correctly you managed to do this, right? Can I ask how?

Thanks for reviewing

**Comment by kmvanbrunt** [comment]
@albertored 
I agree that knowing the return code of a command is useful. However, I'm not ready to accept any solution to this problem until **cmd2** stabilizes and we have time to consider what solution is most universal. Currently **cmd2**'s parsing logic is being completely rewritten, tab completion is being extended with the addition of AutoCompleter, and its being broken up into multiple files.

The need for the feature you suggest does exist. Without it, using ``cmdqueue`` is fairly limited since commands keep running until then end in all cases. Therefore ``load`` can only be used in simple cases. I have typically used the more featured ``pyscript`` command when logic is needed to determine what to do after a command runs. But many times this involves more than a return code since the parsing of a command's output can also be useful in knowing what to do next. I've done this using a ``CmdResult`` class member. This class is defined in cmd2.py and I believe some of the example scripts show its usage. But that approach is probably overkill for a batch mode like you are using.

There are other ways to solve this that need to be examined. Perhaps the solution would include something syntactical like the ``&&`` operator in shells like **bash**. That provides more granularity than the ``exit_with_error_code`` flag which always results in exiting upon command failure. Sometimes a developer cares if a particular command fails and would want to exit, but other times the failure of that same command won't affect the next command in the list and exiting would be the wrong thing to do. Logging is usually enough in those cases.

I believe the best solution will be implemented if we have more time to consider all possibilities.

Thoughts?

**Comment by tleonhardt** [comment]
Ok, how about we leave the Issue related to this open and revisit it after ``cmd2``'s parsing logic has been refactored?

It would be nice to have some standard supported way of returning a non-zero exit code to the shell under certain circumstances.  We just want to be careful about how we implement it.  

One thing to consider is the fact that ``cmd2`` is an extension of ``cmd`` somewhat constrains the kind of architectural changes we can make to support this feature.  Really this is the kind of feature that should be built into ``cmd``, but that is a whole other can of works ;-)

**Comment by albertored** [comment]
It sounds good to me, I'll close this and create a new one when it's time

**Pull request closed without merging**
