### PR TITLE
Add black and isort GitHub Action Workflows

### LINKED ISSUE #930: black, isort, and doc8 - should we use them in our CI?
[black](https://github.com/psf/black) is an extremely popular tool for automatically formatting Python code to match the very opinionated black coding standard.

[isort](https://github.com/timothycrosley/isort) is a tool for automatically sorting Python imports to match a given style.

[doc8](https://github.com/PyCQA/doc8) is a Sphinx style checker.

[mypy](http://mypy-lang.org) is an optional static type checker

Should we incorporate one or more of these tools into our CI process similar to how we have incorporated `flake8`?  Of course, we can tweak the default configuration for each of these tools to make them match our stylistic preferences if we desire.

### PR DESCRIPTION
**Pull request by tleonhardt**
Add `black` and `isort` code formatting checks as part of our continuous integration which run on `push` or `pull_request`.

Also:
- Reformat code according to the configuration for `black` and `isort`

The only code changes in this PR which were not automatic changes made by `black` or `isort` are in the following files:
- `.github/format.yml` - new workflow for black and isort
- `.github/lint.yml` - minor simplifications for flake8
- `Pipfile` - added black as a dev tool
- `pyproject.toml` - added black config
- `setup.cfg` - isort config and updates to flake8 config
- `tasks.py` - update flake8 invoke task

This closes #930

### CODE REVIEW

**Comment by kmvanbrunt** [comment]
This will cause a lot of merge conflicts on the 2.0 branch. Do we want to wait and apply it to that branch instead of master? Are we intending on another 1.5 release?

**Comment by tleonhardt** [comment]
@kmvanbrunt You can run `black` on the 2.0 branch before merging and then it shouldn't cause a lot of merge conflicts.  

But if you are concerned, I'd be happy to just do `isort` for now and add `black` later.

I wanted thoughts from you and @anselor about whether we should do another release prior to 2.0.  I think that depends on how close we are to 2.0 being done.  I'd like to deprecate support for Python 3.5 ASAP and would be happy to do that either in a 1.6.0 release or in a 2.0.0 release.

**Comment by tleonhardt** [comment]
I created #1053 to encompass the configuration changes present in this PR.  The intend is that PR should definitely merge before this one so we can separate the intentional configuration changes from the auto-generated changes made by `black` and/or `isort`

**Comment by tleonhardt** [comment]
@anselor @kmvanbrunt Now that #1053 is merged in, can you test the `black`, `isort`, and `flake8` configurations to make sure they seem OK. 

If they do, then I would like to merge this PR in.

If there are any configuration changes you would like made, I would like to do those as a separate PR first and then modify this one.

**Comment by tleonhardt** [comment]
@kmvanbrunt @anselor I merged the `master` branch into this PR to pick up the changes from the 2.0 branch.  Then I fixed all the conflicts and re-ran `black`, `isort`, `flake8`, and `doc8`.  

Once one of you give this a review, it should be good to merge into `master`.

**Review by tleonhardt — COMMENTED** [review]
I took a detailed look at all changes which are essentially nearly all whitespace changes.

Overall I think I love the changes made by `black` - it provides a consistency and organization of style across all of our codebase.

I'm not in love with our configuration for `isort` where it forces all `from` imports on a separate line even when there is just one.  But I can live with it

**Pull request merged**
