### PR TITLE
Update conditional pyreadline3 dependency for Win

### LINKED ISSUE #1025: pyreadline
I ran into a character encoding issue on Windows installing pyreadline with poetry, but was able to manually install it with pip

In case this would be useful, I found that pyreadline hasn't been updated in 5 years, but there is an active fork, pyreadline3, that should be a drop in replacement. See: https://github.com/brgirgis/pyreadline3

### PR DESCRIPTION
**Pull request by KyleKing**
Fixes #1025

### CODE REVIEW

**Comment by KyleKing** [comment]
The Azure Pipeline tests appear to be failing due to a HTTP 400 on uploading the codecov report. Otherwise those tests pass

```
==> Uploading
    .url https://codecov.io
    .query commit=b45d3d92c536317c47203250924dc080ed659cdf&branch=HEAD&package=py2.1.11
    Gzipping contents..
    Compressed contents to 14885 bytes
    Pinging Codecov...
Error: HTTP 400
Please provide the repository token to upload reports via `-t :repository-token`
```

I'll look into and fix the AppVeyor build. The error is that readline is undefined

**Comment by KyleKing** [comment]
I think this is ready for review! I collapsed the commit into a single one

Let me know if you want me to make any changes

**Review by kmvanbrunt — APPROVED** [review]

**Review by tleonhardt — APPROVED** [review]
We should update the CHANGELOG, but that can be done after this merges in

**Comment by tleonhardt** [comment]
Thanks for the PR @KyleKing !

**Pull request merged**
