### PR TITLE
#698 - Revisiting Color Support

### PR DESCRIPTION
**Pull request by xNinjaKittyx**
Addresses #698 

Changes:
- `poutput` and `perror` no longer use `color` kwarg, which has been split into `fg` and `bg`.
- `fg` and `bg` use human names of color like `blue` or `red`.
- `perror` is split into 2 functions `perror` and `pexcept`. `pexcept` will behave identical to the previous `perror`, but `perror` will only print to stderr with no stacktraces or Exception messages.

### CODE REVIEW

**Comment by tleonhardt** [comment]
Recommend updating test_utils.py to add new unit tests for style_message() so that new utility function has 100% code coverage.

**Comment by tleonhardt** [comment]
Thanks for the PR!  I'll take a look at it tonight.

**Comment by kmvanbrunt** [comment]
I've made a few changes and doc updates. Here are some remaining questions I have:
1. Should `style_message` have an `end` argument? That's not related to style and adding a newline by default when a developer wanted to color a string seems unexpected.
2. I'm uncomfortable going to a string approach for specifying colors. Strings lead to typos that static analyzers won't catch.

**Comment by tleonhardt** [comment]
@xNinjaKittyx By the way, your PR is excellent, so please don't take any offense at other developers collaborating to make it even better.  We might have a moderately peculiar culture here on this project, where it is extremely common for developers to collaborate and work to improve each other's PRs.

**Comment by tleonhardt** [comment]
I like this PR as-is, but I also like the direction @kmvanbrunt is moving in to address the suggestion by @kotfu to decouple the functions for outputting text from the one for styling it and think that is probably a more flexible and maintainable improvement albeit at the cost of a small amount of convenience. 

Some things I think we will need to address once the changes stabilize and before merging into *master* include:

# TODO
* [ ] Update the CHANGELOG
* [ ] Make sure Sphinx docs are still accurate, particularly for section on [output functions](https://cmd2.readthedocs.io/en/latest/unfreefeatures.html?highlight=poutput#poutput-pfeedback-perror-ppaged)
* [ ] Move styling function and associated color dictionaries to a new file called something like **color.py** and add two-stage functions for retrieving the color text which first look in the dictionaries, but then attempt to fallback to getting the color directly from `colorama` using the `getattr` "hack" suggested by @xNinjaKittyx

**Comment by kmvanbrunt** [comment]
@xNinjaKittyx 
Sorry for basically stealing this PR. Issue #698 was based on a conversation I had with @tleonhardt, so I already had some thoughts on the direction we wanted to go.

Then I looked at the [`style()`](https://github.com/pallets/click/blob/a936b99212c69a36a2cc2828252b2c4280c0c88c/click/termui.py#L372) function you posted from **click** and I got very inspired. Since a lot of code needed to be changed, I just went ahead and did it to have it done quickly. Time was an important factor because @tleonhardt and I are doing a **cmd2** talk at PyOhio in a month. I wanted to stabilize the code and give us enough time to make the presentation.

Thanks for your help and don't be discouraged from contributing in the future. I don't usually steal :)

**Comment by xNinjaKittyx** [comment]
@kmvanbrunt It's all good. I'm glad that inspired you :D.
I've never heard about PyOhio, but if they post the content online, I'll make sure to give it a watch.

I use this library quite a bit at work, so I thought I'd contribute when I see something I can do. I'll be on the lookout.

**Comment by tleonhardt** [comment]
@kotfu If you get a chance to look at this, your feedback would be appreciated. 

@xNinjaKittyx Can you please review that changes that @kmvanbrunt and I have made to your PR to make sure they all seem reasonable to you?

**Comment by xNinjaKittyx** [comment]
I think there's a few more breaking changes that might need to be documented.

- the signature of `self.poutput()` and `self.perror()` is now declaring that `end` is a mandatory kwarg now.
- `self.perror()` and the new `pexcept()` no longer have traceback_war, err_color, war_color (I know color is mentioned, but might be helpful to also mention the specific variable names?)

**Pull request merged**
