### PR TITLE
allow_clipboard and other clipboard improvements

### PR DESCRIPTION
**Pull request by kotfu**
PR to address #1225

### CODE REVIEW

**Comment by tleonhardt** [comment]
Any clue why some of the CI stuff is failing?

**Comment by tleonhardt** [comment]
@kotfu I apologize.  I merged the big CR that deprecates support for Python 3.6 and there are now conflicts.  If you have time, can you push an update that resolves the conflicts?  If not I can do it later.

**Comment by kotfu** [comment]
I'll get the conflicts all cleaned up. CI is failing on windows because it claims it doesn't have the current version of pip installed, even though the first step in our CI is to install the current version of pip. I'll see if I can figure that out too.

**Comment by kotfu** [comment]
Conflicts are resolved in the merge, but I still can't figure out why the CI actions on windows are all failing. Each of the failures is in the same spot, and its in the "Install Python Prerequisites" phase. It's complaining that a newer version of pip is available, and suggests a command to update it. Funny thing, it's the exact command that our configuration ran to generate the error. I'm stumped.

**Comment by tleonhardt** [comment]
@kotfu Sometimes the people in charge of the Python tooling ecosystem make me shake my fist in rage and frustration: https://github.com/python/cpython/issues/101153

Potential workaround documented here: https://github.com/pypa/pip/issues/11431

**Pull request merged**
