### PR TITLE
Updated CHANGELOG text regarding recent enhancements to transcript regexes

### PR DESCRIPTION
**Pull request by tleonhardt**
@kotfu Please review what I added to the CHANGELOG related to your recent PR which merged in and change the text as you see fit. 

Also bumped version from 0.7.7a to 0.7.7 in preparation for eventual next release.

Random whitespace changes were made by IDE (probably just stripped spaces on at end of a few lines).

### CODE REVIEW

**Comment by kotfu** [comment]
I tried to commit a change to the update_changelog branch, but I don't have write access. Suggested revisions are in the approval comment.

**Comment by tleonhardt** [comment]
@kotfu Hmm ... I'll look into the settings.  Maybe I screwed up when I added you.  You should have write access to all branches other than master.  Can you please try creating a branch and pushing some change there (you can delete the branch afterwards if you want, just to make sure you can).

**Comment by tleonhardt** [comment]
Oh wait, there is another possibility.  I'm not sure if it is because this repo is within a GitHub organization or because security settings are locked down, but I need to set the origin in a special way in order to have write access within this repo that I don't need to do for personal repos.  I set it like so:

```
git@github.com:python-cmd2/cmd2.git
```

**Comment by kotfu** [comment]
I must have messed something up last time I tried. I was just able to create and checkout a new branch, commit to it, and push it. I was also able to delete the branch.

**Pull request merged**
